'use client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Html } from '@react-three/drei';
import { useMemo, useRef, useState } from 'react';
import * as THREE from 'three';

const dishes = [
 {id:'mutton',name:'Mutton Sukka',kind:'curry',pos:[-1.8,.35,.2] as [number,number,number],color:'#7b2817',img:'/Mutton_chettinad_dish_image_20260928153954.jpg'},
 {id:'chicken',name:'Kongunadu Chicken',kind:'curry',pos:[1.65,.35,.15] as [number,number,number],color:'#b25a23',img:'/Kongunadu_Chicken_preparation_20260928154001.jpg'},
 {id:'biryani',name:'Chettinad Biryani',kind:'biryani',pos:[0,.42,-.75] as [number,number,number],color:'#c89b42',img:'/Chettinad_biryani_dish_20260928154008.jpg'},
 {id:'rasam',name:'Erode Special Rasam',kind:'rasam',pos:[2,.2,-1.35] as [number,number,number],color:'#9c3a1b',img:'/Erode_Rasam_dish_photo_20260928154012.jpg'},
];

function Steam({seed=1}:{seed?:number}){const g=useRef<THREE.Group>(null);useFrame(({clock})=>{if(g.current){g.current.position.y=Math.sin(clock.elapsedTime*.7+seed)*.06}});return <group ref={g}>{Array.from({length:7},(_,i)=><mesh key={i} position={[Math.sin(i*1.9+seed)*.13,i*.11,Math.cos(i*1.4+seed)*.1]}><sphereGeometry args={[.075-i*.006,10,8]}/><meshBasicMaterial color="#fff1d3" transparent opacity={.055}/></mesh>)}</group>}
function Dish({d,selected,onSelect}:{d:any,selected:boolean,onSelect:()=>void}){const r=useRef<THREE.Group>(null);const [hover,setHover]=useState(false);const tex=useMemo(()=>{const t=new THREE.TextureLoader().load(d.img);t.colorSpace=THREE.SRGBColorSpace;const rx=.6;t.repeat.set(rx,1);t.offset.set((1-rx)/2,0);t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.anisotropy=8;return t},[d.img]);useFrame(({clock})=>{if(!r.current)return;r.current.rotation.y+=.0016;r.current.position.y=d.pos[1]+Math.sin(clock.elapsedTime*1.4+d.pos[0])*.035;const s=selected?1.18:hover?1.08:1;r.current.scale.lerp(new THREE.Vector3(s,s,s),.12)});return <group ref={r} position={d.pos} onPointerOver={()=>{setHover(true);document.body.style.cursor='pointer'}} onPointerOut={()=>{setHover(false);document.body.style.cursor='default'}} onClick={(e)=>{e.stopPropagation();onSelect()}}>
 <mesh castShadow receiveShadow><cylinderGeometry args={[.74,.55,.12,56]}/><meshStandardMaterial color="#4f3a1d" metalness={.92} roughness={.28}/></mesh>
 <mesh position={[0,.088,0]} rotation={[Math.PI/2,0,0]} castShadow><torusGeometry args={[.72,.05,16,64]}/><meshStandardMaterial color="#8a6631" metalness={.95} roughness={.22}/></mesh>
 <mesh position={[0,-.08,0]} scale={[1,.4,1]}><sphereGeometry args={[.58,32,20]}/><meshStandardMaterial color="#241a12" roughness={.95}/></mesh>
 <mesh position={[0,.16,0]} rotation={[-Math.PI/2,0,0]} castShadow><circleGeometry args={[.6,72]}/><meshStandardMaterial map={tex} roughness={.72} metalness={.02} emissive={d.color} emissiveIntensity={.04}/></mesh>
 <Steam seed={d.pos[0]}/>
 {(hover||selected)&&<Html center><div className="scene-label"><img src={d.img} alt={d.name}/><small>{selected?'SELECTED':'DISCOVER'}</small><strong>{d.name}</strong><span>{selected?'SCROLL TO JOURNEY':'CLICK TO TASTE'}</span></div></Html>}
</group>}
function Embers(){const ref=useRef<THREE.Points>(null);const count=110;const geo=useMemo(()=>{const arr=new Float32Array(count*3);const sp=new Float32Array(count);for(let i=0;i<count;i++){arr[i*3]=(Math.random()-.5)*9;arr[i*3+1]=Math.random()*5.5;arr[i*3+2]=(Math.random()-.5)*9;sp[i]=.15+Math.random()*.4}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(arr,3));(g as any)._sp=sp;return g},[]);useFrame((_,dt)=>{if(!ref.current)return;const pos=ref.current.geometry.attributes.position as THREE.BufferAttribute;const sp=(ref.current.geometry as any)._sp as Float32Array;for(let i=0;i<count;i++){let y=pos.getY(i)+dt*sp[i];if(y>5.5)y=-.2;pos.setY(i,y);pos.setX(i,pos.getX(i)+Math.sin(y*2+i)*.002)}pos.needsUpdate=true;ref.current.rotation.y+=.0003});return <points ref={ref} geometry={geo}><pointsMaterial size={.05} color="#ffb45e" transparent opacity={.55} depthWrite={false} sizeAttenuation/></points>}
function Camera({progress,selected}:{progress:number,selected:string|null}){const {camera}=useThree();const look=useRef(new THREE.Vector3(0,.28,0));useFrame(({pointer,clock})=>{const p=THREE.MathUtils.clamp(progress,0,1);const ang=-.2+p*1.9+Math.sin(clock.elapsedTime*.05)*.04;const rad=6.7-p*3.1;const hgt=1.45+Math.sin(p*Math.PI)*1.15;const sel=selected?dishes.find(d=>d.id===selected):null;const cx=Math.sin(ang)*rad+pointer.x*.6+(sel?.pos[0]||0)*.2;const cz=Math.cos(ang)*rad;const cy=hgt+pointer.y*-.3;camera.position.lerp(new THREE.Vector3(cx,cy,cz),.05);const ty=sel?sel.pos[1]+.15:.28;look.current.lerp(new THREE.Vector3((sel?.pos[0]||0)*.4,ty,(sel?.pos[2]||0)*.4),.05);camera.lookAt(look.current)});return null}
function Floor(){const tex=useMemo(()=>{const t=new THREE.TextureLoader().load('/Seamless_wood_surface_tile_20260928154047.jpg');t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2.4,2.4);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t},[]);return <mesh rotation={[-Math.PI/2,0,0]} receiveShadow><circleGeometry args={[4.2,96]}/><meshStandardMaterial map={tex} color="#caa876" roughness={.85} metalness={.05}/></mesh>}
function World({progress,selected,onSelect}:{progress:number,selected:string|null,onSelect:(id:string)=>void}){return <><fog attach="fog" args={['#1a1109',5,16]}/><ambientLight intensity={.6}/><hemisphereLight args={['#f0d9a8','#2a1c10',.5]}/><spotLight position={[0,6,4]} intensity={160} angle={.42} penumbra={1} color="#ffe2aa" castShadow/><pointLight position={[-4,1,2]} intensity={30} color="#c9552a"/><pointLight position={[4,2,-2]} intensity={24} color="#d39a42"/><group><Floor/>{dishes.map(d=><Dish key={d.id} d={d} selected={selected===d.id} onSelect={()=>onSelect(d.id)}/>)}</group><Embers/><Camera progress={progress} selected={selected}/></>}
export default function FeastScene({progress,selected,onSelect}:{stage?:number,progress:number,selected:string|null,onSelect:(id:string)=>void}){return <div className="scene-shell"><Canvas shadows dpr={[1,1.7]} gl={{alpha:true}} camera={{position:[0,1.45,6.7],fov:40}}><World progress={progress} selected={selected} onSelect={onSelect}/></Canvas><div className="scene-hud"><b>THE FEAST TABLE</b><span>DRAG TO LOOK · CLICK A DISH · SCROLL TO JOURNEY</span></div></div>}
